name: Update Static Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-5'

jobs:
  UpdateXKCDData:
    name: Update XKCD Data
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: NM-EEA-Y
      GITHUB_EMAIL: contact@skyra.pw
      GITHUB_TOKEN: ${{ secrets.SKYRA_TOKEN }}
    steps:
      - name:
        run: |
          git config --local user.email "${GITHUB_EMAIL}";
          git config --local user.name "${GITHUB_USER}";
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SKYRA_TOKEN }}
      - name: Use Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Dependencies
        run: yarn --immutable
      - name: Run the XKCD Extraction script
        run: node ./scripts/update-xkcd-entries.mjs
      - name: Commit any changes and create a pull request
        run: |
          git add .;
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit, exiting with code 0"
            exit 0;
          else
            git remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git";
            git commit -sam "refactor: update xkcd data";
            git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD);
          fi
